//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireTestingApp.DataApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAnswer
    {
        public int UserAnswerID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public Nullable<int> AnswerID { get; set; }
        public bool IsCorrect { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
    }
}
