USE master
GO

CREATE DATABASE FireExamAppDB
GO

USE FireExamAppDB
GO

CREATE TABLE Roles
(
	RoleID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Rolename NVARCHAR(20) NOT NULL
)
GO

CREATE TABLE TestStatuses
(
	StatusID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Statusname NVARCHAR(10) NOT NULL
)
GO

CREATE TABLE Users
(
	UserID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Firstname NVARCHAR(50) NOT NULL,
	Lastname NVARCHAR(50) NOT NULL,
	Surname NVARCHAR(50) NULL,
	RoleID INT FOREIGN KEY REFERENCES Roles(RoleID) NOT NULL,
	UserLogin NVARCHAR(50) UNIQUE NOT NULL,
	UserPassword NVARCHAR(12) NOT NULL,
)
GO

CREATE TABLE Questions
(
	QuestionID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	QuestionText NVARCHAR(MAX) NOT NULL
)
GO

CREATE TABLE Answers
(
	AnswerID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	QuestionID INT FOREIGN KEY REFERENCES Questions(QuestionID) NOT NULL,
	AnswerText NVARCHAR(MAX) NOT NULL,
	IsCorrectAnswer BIT NOT NULL
)
GO

CREATE TABLE Results
(
	ResultID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	UserID INT FOREIGN KEY REFERENCES Users(UserID) NOT NULL,
	TestDate DATETIME2 DEFAULT GETDATE() NOT NULL,
	UserScore INT NOT NULL,
	StatusID INT FOREIGN KEY REFERENCES TestStatuses(StatusID) NOT NULL
)
GO

CREATE TABLE UserAnswers 
(
    UserAnswerID INT IDENTITY PRIMARY KEY,
	AnswerDate DATETIME2 NOT NULL,
    UserID INT FOREIGN KEY REFERENCES Users(UserID),
    QuestionID INT FOREIGN KEY REFERENCES Questions(QuestionID),
    AnswerID INT FOREIGN KEY REFERENCES Answers(AnswerID),
    IsCorrect BIT NOT NULL

)
GO

CREATE TABLE Tickets
(
	TicketID INT PRIMARY KEY NOT NULL,
	FromUserID INT FOREIGN KEY REFERENCES Users(UserID) NOT NULL,
	TicketDate DATETIME2 NOT NULL,
	TicketText NVARCHAR(MAX) NOT NULL
)